# Default values for mgob.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
# Note that two backup plans are provided as templates - they contain dummy values and should be changed before
# attempting to apply the chart to your cluster.
replicaCount: 1
image:
  repository: stefanprodan/mgob
  pullPolicy: IfNotPresent

  # We need edge to be able to use the "configMap.data[name].target.params", required to set the auth db.
  # When this is official, update to the proper stable release.
  #
  # @see https://github.com/stefanprodan/mgob/commit/b70e86b3acba8c82447a568cfcdd31fbd5ee3f7c
  tag: "0.10"
service:
  name: mgob
  externalPort: 8090
  internalPort: 8090
selector:
  role: mongo-backup
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
storage:
  longTerm:
    accessMode: "ReadWriteOnce"
    storageClass: "default-retain"
    name: "mgob-storage"
    size: 10Gi
  tmp:
    accessMode: "ReadWriteOnce"
    storageClass: "default-retain"
    name: "mgob-tmp"
    size: 3Gi
configMap:
  name: "mgob-config"
  data:
    # Add each plan as per below.
    ConnectorDb.yml: |
      target:
        host: "shared-mongodb"
        port: 27017
        database: "ConnectorDb"
        username: "mongodb-backup"
        password: "mongodb-backup"
        params: "--authenticationDatabase admin"
      scheduler:
        cron: "0 5 * * *"
        retention: 7
        timeout: 60

    mstask.yml: |
      target:
        host: "shared-mongodb"
        port: 27017
        database: "mstask"
        username: "mongodb-backup"
        password: "mongodb-backup"
        params: "--authenticationDatabase admin"
      scheduler:
        cron: "0 5 * * *"
        retention: 7
        timeout: 60

    local.yml: |
      target:
        host: "shared-mongodb"
        port: 27017
        database: "local"
        username: "mongodb-backup"
        password: "mongodb-backup"
        params: "--authenticationDatabase admin"
      scheduler:
        cron: "0 5 * * *"
        retention: 7
        timeout: 60
secret: {}
## You can either insert your secret values as part of helm values, or refer externally created secrets.
#- name: gcp-example-secret-name
#- name: gcp-example-secret-name-with-values
#  data:
#    service-account.json: |
#      {
#        "type": "service_account",
#        "project_id": "your-gcp-project-id",
#        "private_key_id": "12345678901234567890",
#        "private_key": "-----BEGIN PRIVATE KEY-----\n...........\n-----END PRIVATE KEY-----\n",
#        ...
#      }
env: {}
#- name: HTTPS_PROXY
#  value: "http://localhost:3128"
